name: MultiSpawnPlus
main: io.github.ultimatedillon.multispawnplus.MultiSpawnPlus
version: 0.2.1
author: UltimateDillon
description: MultiSpawnPlus
commands:
  multispawnplus:
    description: The base command for all things MultiSpawnPlus.
    aliases: [msp]
    usage:  |
            Usage:
            /<command> add <name>
            /<command> delete <name>
            /<command> spawn <name>
            /<command> reload
permissions:
  multispawnplus.*:
    description: Gives access to all features of MultiSpawnPlus.
    children:
      multispawnplus.add: true
      multispawnplus.delete: true
      multispawnplus.spawn: true
      multispawnplus.reload: true